version: '3.2'
services:
  web:
    depends_on:
      - db
    volumes:
      - ./docker/local/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    build:
      dockerfile: ./docker/local/dockerfiles/dockerfile_php7
    links:
      - db
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
  db:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./docker/data/mysql:/var/lib/mysql

